/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-11 07:46:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.88.1\">\n");
      out.write("<title>ascent</title>\n");
      out.write("\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.1/examples/headers/\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link href=\"../assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".bd-placeholder-img {\n");
      out.write("	font-size: 1.125rem;\n");
      out.write("	text-anchor: middle;\n");
      out.write("	-webkit-user-select: none;\n");
      out.write("	-moz-user-select: none;\n");
      out.write("	user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("	.bd-placeholder-img-lg {\n");
      out.write("		font-size: 3.5rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link href=\"headers.css\" rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<title>ascent</title>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("#nav{				/*1단바 */\n");
      out.write("	list-style:none; /* 불릿 없애기 */\n");
      out.write("	height:10px;\n");
      out.write("	padding:5px 1px;\n");
      out.write("	margin:0;\n");
      out.write("	background:#FFFAF6;\n");
      out.write("}\n");
      out.write("#nav li{ /*전체 메뉴의 리스트에 대한 스타일*/\n");
      out.write("	float:left; /*-- 메뉴를 왼쪽부터 표시*/\n");
      out.write("	posiotion:relative; /*-- 순서대로 표시*/\n");
      out.write("	margin:5px 30px;\n");
      out.write("	padding:0;\n");
      out.write("}\n");
      out.write("#nav li a {		/*메인 메뉴 링크의 스타일*/\n");
      out.write("	display:block; /*메뉴칸을 블록레벨로 만듬*/\n");
      out.write("	font-family:\"나눔명조\";\n");
      out.write("	font-size:20px;			/*메인메뉴의 글씨 크기*/\n");
      out.write("	padding:7px 8px;\n");
      out.write("	margin:0;\n");
      out.write("	color:#463D3D; /*글자색 지정*/\n");
      out.write("	margin:0;\n");
      out.write("	text-decoration:none; /*글자의 밑줄 없애기*/\n");
      out.write("}\n");
      out.write("#nav li:hover >a { /*메인메뉴링크에 마우스 포인터 올렸을 떄 스타일 */\n");
      out.write(" 	background:#FFCAB2;\n");
      out.write("	color:#463D3D; /*글자색 지정*/\n");
      out.write("	margin:0;\n");
      out.write("	padding:5px;\n");
      out.write("}\n");
      out.write("#nav ul{ /*서브메뉴 스타일*/\n");
      out.write("	list-style:none; /* 불릿 없애기 */\n");
      out.write("	margin:0;\n");
      out.write("	padding:0;\n");
      out.write("	posiotion:absolute; /*고정위치에 표시 */\n");
      out.write("	left:0;			/*부모 요소와 왼쪽 좌표값을 같게 한다 */\n");
      out.write("	top:40px;\n");
      out.write("	width:110px;	/*서브메뉴의 너비*/\n");
      out.write("	background:#FFFAF6;		/*서브 메뉴의 배경색*/\n");
      out.write("	text-align:center;\n");
      out.write("	opacity:0;   /*평상시에 안보이게 */\n");
      out.write("}\n");
      out.write("#nav li:hover ul{ /*메인메뉴에 마우스 포인터를 올려놨을 떄 서브 메뉴 스타일*/\n");
      out.write("	opacity:1; /*서브메뉴 보이게 설정*/\n");
      out.write("}\n");
      out.write("#nav li:hover ul li{ /*마우스 포인터를 올려놨을 떄 서브메뉴 스타일*/\n");
      out.write("	height:35px; /*서브메뉴의 높이*/\n");
      out.write("	overflow:visible;  /*영역을 넘어가는 내용이 있다면 표시*/\n");
      out.write("	padding:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#nav ul li{  /*서브메뉴 리스트들의 스타일*/			\n");
      out.write("	float:none; /*부모요소의 떠있는 속성을 해제하여 세로정렬*/\n");
      out.write("	margin:0;\n");
      out.write("	padding:0;\n");
      out.write("	font-size:10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#navBar{				/*navbar 크기, 조정  */\n");
      out.write("	background:#FFFAF6;	\n");
      out.write("	height:141px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-divider {\n");
      out.write("	height: 3rem;\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\n");
      out.write("	border-width: 1px 0;\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\n");
      out.write("		rgba(0, 0, 0, .15);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-control-dark {\n");
      out.write("	color: #fff;\n");
      out.write("	background-color: var(- -bs-dark);\n");
      out.write("	border-color: var(- -bs-gray);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-control-dark:focus {\n");
      out.write("	color: #fff;\n");
      out.write("	background-color: var(- -bs-dark);\n");
      out.write("	border-color: #fff;\n");
      out.write("	box-shadow: 0 0 0 .25rem rgba(255, 255, 255, .25);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bi {\n");
      out.write("	vertical-align: -.125em;\n");
      out.write("	fill: currentColor;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-toggle {\n");
      out.write("	outline: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bd-placeholder-img {\n");
      out.write("	font-size: 1.125rem;\n");
      out.write("	text-anchor: middle;\n");
      out.write("	-webkit-user-select: none;\n");
      out.write("	-moz-user-select: none;\n");
      out.write("	user-select: none;\n");
      out.write("}\n");
      out.write(".container{				/*class라서 ., 로고 아이디로 위치 수정 */\n");
      out.write("      	position: absolute;\n");
      out.write("      	top : 50%;\n");
      out.write("      	left : 50%;\n");
      out.write("      	transform : translate(-50%,-50%);\n");
      out.write("      }\n");
      out.write("#hyper1{				/*id는 샵, 동영상 가운데 제목  아이디로 위치 수정 */\n");
      out.write("      	position: absolute;\n");
      out.write("      	top : 60%;\n");
      out.write("      	left : 50%;\n");
      out.write("      	transform : translate(-50%,-50%);\n");
      out.write("      	font-size: 40px;\n");
      out.write("      	font-family:\"나눔명조\";  /*하이퍼 글씨  */\n");
      out.write("      	color:#FFFAF6;\n");
      out.write("      }\n");
      out.write("#hyper2{				/*id는 샵 동영상 하이퍼링크 아이디로 위치 수정 */\n");
      out.write("      	position: absolute;\n");
      out.write("      	top : 68%;\n");
      out.write("      	left : 50%;\n");
      out.write("      	transform : translate(-50%,-50%);\n");
      out.write("      	font-size: 24px;\n");
      out.write("      	font-family:\"나눔명조\";\n");
      out.write("      	color:#FFFAF6;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("	.bd-placeholder-img-lg {\n");
      out.write("		font-size: 3.5rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<style><!--아이콘 -->\n");
      out.write(".bi-search{		/*검색*/\n");
      out.write("	font-size: 32px;\n");
      out.write("	line-height:32px;\n");
      out.write("	color: #463D3D;\n");
      out.write("}\n");
      out.write(".bi-search-heart{		/*검색클릭 후*/\n");
      out.write("	font-size: 32px;\n");
      out.write("	line-height: 32px;\n");
      out.write("	color: #463D3D;\n");
      out.write("}\n");
      out.write(".bi-person-fill {		/*마이페이지*/\n");
      out.write("	font-size: 32px;\n");
      out.write("	line-height: 32px;\n");
      out.write("	color:#463D3D;\n");
      out.write("}\n");
      out.write(".bi-bag-heart {			/*장바구니*/\n");
      out.write("	font-size: 32px;\n");
      out.write("	line-height: 32px;\n");
      out.write("	color: #463D3D;\n");
      out.write("}\n");
      out.write(".bi-bag-check-fill {	/*장바구니클릭 후*/\n");
      out.write("	font-size: 32px;\n");
      out.write("	line-height: 32px;\n");
      out.write("	color:#463D3D;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("     \n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<!-- 비디오 -->\n");
      out.write("<style>\n");
      out.write("#videobcg {\n");
      out.write("	position: relative;\n");
      out.write("	top:0px;\n");
      out.write("	left:-15px;\n");
      out.write("	min-width:100%;\n");
      out.write("	min-height:100%;\n");
      out.write("	padding-bottom:70px;\n");
      out.write("	height:auto;\n");
      out.write("	margin:0;\n");
      out.write("	z-index:-1000;\n");
      out.write("}\n");
      out.write("/*상품구현 위치 */\n");
      out.write("#container1 {\n");
      out.write("		position: relative;\n");
      out.write("		top:300px;\n");
      out.write("		\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	<nav id=\"navBar\" class=\"navbar navbar-expand-lg navbar\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("				aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("					\n");
      out.write("						<!-- 상품 카테고리 한눈에 차라락 보여주기  -->\n");
      out.write("					\n");
      out.write("					<ul id=\"nav\">\n");
      out.write("					<li><a class=\"nav-link\" href=\"#\">Shop</a>\n");
      out.write("						<ul>\n");
      out.write("							\n");
      out.write("							<li><a href=\"Pplist.do\">Floral</a></li>\n");
      out.write("							<li><a href=\"#\">Citrus</a></li>\n");
      out.write("							<li><a href=\"#\">Fresh</a></li>\n");
      out.write("							<li><a href=\"#\">Fruity</a></li>\n");
      out.write("							<li><a href=\"#\">Woody</a></li>\n");
      out.write("							<li><a href=\"#\">Oriental</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write("						<!-- 상품별로 보여주기  -->\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							Perfume </a>\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Eau de perfume</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Eau de toillette</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Eau de cologne</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Body Spray</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					<!-- 1:1문의 ,공지사항, 상품문의  -->\n");
      out.write("					<li><a class=\"nav-link px-2\" href=\"#\">About</a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#\">Notice</a></li>\n");
      out.write("							<li><a href=\"#\">Q&A</a></li>\n");
      out.write("						</ul>\n");
      out.write("						\n");
      out.write("						\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				</ul>\n");
      out.write("				<!--로고 -->\n");
      out.write("			\n");
      out.write("      			  <div class=\"container col-12 col-lg-auto me-lg-auto mb-2 mb-md-0\">\n");
      out.write("   					 <a class=\"navbar-brand\" href=\"#\">\n");
      out.write("   					   <img src=\"assets/logo.png\"  alt=\"\" width=\"300\" height=\"150\">\n");
      out.write("  					  </a>\n");
      out.write("				  </div>\n");
      out.write("      			  \n");
      out.write("      			  \n");
      out.write("      			 <!--검색하기  -->\n");
      out.write("				<form  class=\"d-flex\">\n");
      out.write("					<input class=\"form-control me-2\" type=\"search\" placeholder=\"검색하기\" aria-label=\"Search\"> \n");
      out.write("				</form>\n");
      out.write("				<!--검색,마이페이지,장바구니 아이콘  -->\n");
      out.write("				<div class=\"text-end\">\n");
      out.write("					<k class=\"bi bi-search\" style=\"font-size:2.1rem; cursor: pointer;\" href=\"#\"></k>\n");
      out.write("					<script>\n");
      out.write("					var k = 0;\n");
      out.write("					$('k').on('click', function() {\n");
      out.write("						if (k == 0) {\n");
      out.write("							$(this).attr('class', 'bi-search-heart');\n");
      out.write("							k++;\n");
      out.write("						} else if (k == 1) {\n");
      out.write("							$(this).attr('class', 'bi-search');\n");
      out.write("							k--;\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("				</script>\n");
      out.write("					<i class=\"bi bi-person-fill\" style=\"font-size:2.5rem;cursor: pointer; \" href=\"#\"></i>\n");
      out.write("					<j class=\"bi bi-bag-heart\" style=\"font-size:2.3rem; cursor: pointer;\" href=\"#\"></j>\n");
      out.write("\n");
      out.write("				<script>\n");
      out.write("					var j = 0;\n");
      out.write("					$('j').on('click', function() {\n");
      out.write("						if (j == 0) {\n");
      out.write("							$(this).attr('class', 'bi-bag-check-fill');\n");
      out.write("							j++;\n");
      out.write("						} else if (j == 1) {\n");
      out.write("							$(this).attr('class', 'bi-bag-heart');\n");
      out.write("							j--;\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("				</script>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	\n");
      out.write("		<!-- 비디오1  -->\n");
      out.write("		<!-- 비디오에 하이퍼링크 띄우기  -->\n");
      out.write("		<ul>\n");
      out.write("		<video id=\"videobcg\" width=\"100%\" height=\"480\"  autoplay loop muted>\n");
      out.write("			<source	src=\"assets/pexels-rose.mp4\" type=\"video/mp4\" >\n");
      out.write("		</video>\n");
      out.write("			<div class=\"jb-text\">\n");
      out.write("      	  <p id=\"hyper1\">가드니아의 여름</p>\n");
      out.write("    	  </div>\n");
      out.write("		<a id=\"hyper2\" href=\"#\">More </a>		\n");
      out.write("		</ul>\n");
      out.write("		\n");
      out.write("	<!-- 상품 구현  -->\n");
      out.write("	    <!-- Section-->\n");
      out.write("        <section id=\"container1\" class=\"py-5\">\n");
      out.write("        \n");
      out.write("            <div class=\"container px-4 px-lg-10 mt-5\">\n");
      out.write("            \n");
      out.write("                <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\n");
      out.write("                    <div class=\"col mb-5\">\n");
      out.write("                        <div class=\"card h-100\">\n");
      out.write("                            <!-- Product image-->\n");
      out.write("                            <img class=\"card-img-top\" src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\n");
      out.write("                            <!-- Product details-->\n");
      out.write("                            <div class=\"card-body p-4\">\n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                    <!-- Product name-->\n");
      out.write("                                    <h5 class=\"fw-bolder\">Perfume</h5>\n");
      out.write("                                    <!-- Product price-->\n");
      out.write("                             		50ml - 240000원 \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Product actions-->\n");
      out.write("                            <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\n");
      out.write("                                <div class=\"text-center\"><a class=\"btn btn-outline-dark mt-auto\" href=\"#\">옵션 보기 </a></div>\n");
      out.write("                                <br>\n");
      out.write("                                <!-- 찜  -->\n");
      out.write("                                 <div class=\"text-center\"><j class=\"text-center bi bi-heart\" style=\"font-size:1.7rem;cursor: pointer;\" href=\"#\"></j></div>\n");
      out.write("                                \n");
      out.write("                                <script>\n");
      out.write("                                var j = 0;\n");
      out.write("            					$('j').on('click', function() {\n");
      out.write("            						if (j == 0) {\n");
      out.write("            							$(this).attr('class', 'bi-heart-fill');\n");
      out.write("            							j++;\n");
      out.write("            						} else if (j == 1) {\n");
      out.write("            							$(this).attr('class', 'bi-heart');\n");
      out.write("            							j--;\n");
      out.write("            						}\n");
      out.write("            					});\n");
      out.write("                                \n");
      out.write("                                </script>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    <div class=\"col mb-5\">\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                        <div class=\"card h-100\">\n");
      out.write("                            <!-- Sale badge-->\n");
      out.write("                            <div class=\"badge bg-dark text-white position-absolute\" style=\"top: 0.5rem; right: 0.5rem\">신상품</div>\n");
      out.write("                            <!-- Product image-->\n");
      out.write("                            <img class=\"card-img-top\" src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\n");
      out.write("                            <!-- Product details-->\n");
      out.write("                            <div class=\"card-body p-4\">\n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                    <!-- Product name-->\n");
      out.write("                                    <h5 class=\"fw-bolder\">Special Item</h5>\n");
      out.write("                                    <!-- Product reviews-->\n");
      out.write("                                    <div class=\"d-flex justify-content-center small text-warning mb-2\">\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star\"></div>\n");
      out.write("                                        <div class=\"bi-star\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Product price-->\n");
      out.write("                                    <span class=\"text-muted text-decoration-line-through\">$20.00</span>\n");
      out.write("                                    340000원 \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Product actions-->\n");
      out.write("                            <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\n");
      out.write("                                <div class=\"text-center\"><a class=\"btn btn-outline-dark mt-auto\" href=\"#\">장바구니에 담기 </a></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col mb-5\">\n");
      out.write("                        <div class=\"card h-100\">\n");
      out.write("                            <!-- Sale badge-->\n");
      out.write("                            <div class=\"badge bg-dark text-white position-absolute\" style=\"top: 0.5rem; right: 0.5rem\">Best</div>\n");
      out.write("                            <!-- Product image-->\n");
      out.write("                            <img class=\"card-img-top\" src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\n");
      out.write("                            <!-- Product details-->\n");
      out.write("                            <div class=\"card-body p-4\">\n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                    <!-- Product name-->\n");
      out.write("                                    <h5 class=\"fw-bolder\">Sale Item</h5>\n");
      out.write("                                    <!-- Product price-->\n");
      out.write("                                    <span class=\"text-muted text-decoration-line-through\">$50.00</span>\n");
      out.write("                                    $25.00\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Product actions-->\n");
      out.write("                            <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\n");
      out.write("                                <div class=\"text-center\"><a class=\"btn btn-outline-dark mt-auto\" href=\"#\">장바구니에 담기</a></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col mb-5\">\n");
      out.write("                        <div class=\"card h-100\">\n");
      out.write("                            <!-- Product image-->\n");
      out.write("                            <img class=\"card-img-top\" src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\n");
      out.write("                            <!-- Product details-->\n");
      out.write("                            <div class=\"card-body p-4\">\n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                    <!-- Product name-->\n");
      out.write("                                    <h5 class=\"fw-bolder\">Popular Item</h5>\n");
      out.write("                                    <!-- Product reviews-->\n");
      out.write("                                    <div class=\"d-flex justify-content-center small text-warning mb-2\">\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Product price-->\n");
      out.write("                                    $40.00\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Product actions-->\n");
      out.write("                            <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\n");
      out.write("                                <div class=\"text-center\"><a class=\"btn btn-outline-dark mt-auto\" href=\"#\">Add to cart</a></div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                   \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
