/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-13 06:31:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class logInV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.88.1\">\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.1/examples/headers/\">\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link href=\"../assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link href=\"headers.css\" rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("	\n");
      out.write("<link type=\"text/css\" href=\"css/productlist.css\" rel=\"stylesheet\" >\n");
      out.write("\n");
      out.write("<title>Log In</title>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("	.contents{\n");
      out.write("		position: absolute;\n");
      out.write("		left : 50%;\n");
      out.write("		transform : translate(-50%,0%);\n");
      out.write("		padding: 50px ;\n");
      out.write("		font-family: \"나눔명조\";\n");
      out.write("		color:#463D3D;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#warning{\n");
      out.write("		color: #999191;\n");
      out.write("		font-size: 12px;\n");
      out.write("		text-align: center;\n");
      out.write("		font-family: \"나눔명조\"\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#hyper{				\n");
      out.write("      	font-size: 14px;\n");
      out.write("      	font-family:\"나눔명조\";\n");
      out.write("      	color:#463D3D;\n");
      out.write("      	TEXT-DECORATION:none;\n");
      out.write("      }\n");
      out.write("   	\n");
      out.write("   	input{\n");
      out.write("   		margin:7px 0px;\n");
      out.write("   		width:224px;\n");
      out.write("	    height:32px;\n");
      out.write("   	}\n");
      out.write("   	\n");
      out.write("    button{\n");
      out.write("	    background-color: #F7CCB6;\n");
      out.write("	    color: #463D3D;\n");
      out.write("	    border: 1px solid #999191;\n");
      out.write("	    /* font-size: 1.0em; */\n");
      out.write("	    letter-spacing: 0px;\n");
      out.write("	    padding: 5px 0 0 0px;\n");
      out.write("	    cursor: pointer;\n");
      out.write("	    display: inline-block;\n");
      out.write("	   	margin-bottom : 10px;\n");
      out.write("	    transition: all 0.5s;    \n");
      out.write("	    width:224px;\n");
      out.write("	    height:32px;\n");
      out.write("	}\n");
      out.write("	button:hover{\n");
      out.write("	    background: #241571;\n");
      out.write("	    color: #FFFAF6;\n");
      out.write("	    transition: all 0.5s;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script id=\"alert\" type=\"text/javascript\">\n");
      out.write("	let alertTxt = '");
      out.print((String)session.getAttribute("alertTxt"));
      out.write("' ;\n");
      out.write("	if(alertTxt !== \"null\"){\n");
      out.write("		alert(alertTxt);\n");
      out.write("		");

		session.invalidate();
		
      out.write("\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/* 필수입력  */\n");
      out.write("	function checkid(){\n");
      out.write("		let id = document.getElementById(\"userID\").value;\n");
      out.write("		let pw = document.getElementById(\"userPW\").value;\n");
      out.write("		let warning = document.getElementById(\"Warning\");\n");
      out.write("\n");
      out.write("		if(id == \"\"){\n");
      out.write("			warning.innerHTML = '<p id=\"warning\"> 아이디를 입력해주세요 </p>';\n");
      out.write("			return document.log.userID.focus();\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		if(pw == \"\"){\n");
      out.write("			warning.innerHTML = '<p id=\"warning\"> 비밀번호를 입력해주세요 </p>';\n");
      out.write("			return document.log.userPW.focus();\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("		 document.log.submit();			\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function noblank(obj) { // 공백사용못하게\n");
      out.write("	    var str_space = /\\s/;  // 공백체크\n");
      out.write("	    if(str_space.exec(obj.value)) { //공백 체크\n");
      out.write("	        /* alert(\"해당 항목에는 공백을 사용할수 없습니다.\\n\\n공백은 자동적으로 제거 됩니다.\"); */\n");
      out.write("	        obj.focus();\n");
      out.write("	        obj.value = obj.value.replace(' ',''); // 공백제거\n");
      out.write("	        return false;\n");
      out.write("	    }\n");
      out.write("	 // onkeyup=\"noSpaceForm(this);\" onchange=\"noSpaceForm(this);\"\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<body style=\"background-color:#FFFAF6\">\n");
      out.write("\n");
      out.write("<!-- 메인홈바 -->\n");
      out.write("	<nav id=\"navBar\" class=\"navbar navbar-expand-lg navbar\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("				aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("					\n");
      out.write("				<!-- 상품 카테고리 한눈에 차라락 보여주기  -->\n");
      out.write("				<ul id=\"nav\">\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle\"  id=\"navbarDropdown\"\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							Scent </a>\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"allList.do\">All</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sFList.do\">Floral</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sCList.do\">Citrus</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sFRList.do\">Fresh</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sFTList.do\">Fruity</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sWList.do\">Woody</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sOList.do\">Oriental</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li> \n");
      out.write("				<!-- 상품별로 보여주기  -->\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\"\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							Perfume </a>\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"allList.do\">All</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pPList.do\">Eau de perfume</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pTList.do\">Eau de toilette</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pCList.do\">Eau de cologne</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pBList.do\">Body Spray</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					<!-- 1:1문의 ,공지사항, 상품문의  -->\n");
      out.write("					<li><a class=\"nav-link px-2\" href=\"#\" style=\"width: 100px;\">About</a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"noticeBoardList.do\" style=\"width: 100px;\">Notice</a></li>\n");
      out.write("							<!-- <li><a href=\"counselList.do\">Q&A</a></li> -->\n");
      out.write("							<li><a href=\"logInV.jsp\" style=\"width: 100px;\">Q&A</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				</ul>\n");
      out.write("				<!--로고 -->\n");
      out.write("      			  <div class=\"container col-12 col-lg-auto me-lg-auto mb-2 mb-md-0\">\n");
      out.write("   					 <a class=\"navbar-brand\" href=\"main.do\">\n");
      out.write("   					   <img src=\"assets/logo.png\"  alt=\"\" width=\"300\" height=\"150\">\n");
      out.write("  					  </a>\n");
      out.write("				  </div>\n");
      out.write("      			 <!--검색하기  -->\n");
      out.write("				<form  class=\"d-flex\">\n");
      out.write("					<input class=\"form-control me-2\" type=\"search\" placeholder=\"검색하기\" aria-label=\"Search\"> \n");
      out.write("				</form>\n");
      out.write("				<!--검색,마이페이지,장바구니 아이콘  -->\n");
      out.write("				<div class=\"text-end\">\n");
      out.write("					<k class=\"bi bi-search\" style=\"font-size:2.1rem; cursor: pointer;\" href=\"#\"></k>\n");
      out.write("					<script>\n");
      out.write("					var k = 0;\n");
      out.write("					$('k').on('click', function() {\n");
      out.write("						if (k == 0) {\n");
      out.write("							$(this).attr('class', 'bi-search-heart');\n");
      out.write("							k++;\n");
      out.write("						} else if (k == 1) {\n");
      out.write("							$(this).attr('class', 'bi-search');\n");
      out.write("							k--;\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("				</script>\n");
      out.write("					<i class=\"bi bi-person-fill\" style=\"font-size:2.5rem;cursor: pointer;\" onclick = \"location.href='logInV.jsp'\" ></i>\n");
      out.write("					<j  class=\"bi bi-bag-heart\" style=\"font-size:2.3rem; cursor: pointer;\" href=\"#\"></j>\n");
      out.write("\n");
      out.write("				<script>\n");
      out.write("					var j = 0;\n");
      out.write("					$('j').on('click', function() {\n");
      out.write("						if (j == 0) {\n");
      out.write("							$(this).attr('class', 'bi-bag-check-fill');\n");
      out.write("							j++;\n");
      out.write("						} else if (j == 1) {\n");
      out.write("							$(this).attr('class', 'bi-bag-heart');\n");
      out.write("							j—;\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("				</script>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("\n");
      out.write(" <div class=\"contents\">\n");
      out.write("\n");
      out.write("	<div>\n");
      out.write("		<h1>LOG IN</h1>\n");
      out.write("	</div>  \n");
      out.write(" \n");
      out.write(" 	<div >\n");
      out.write(" 		<form action=\"logIn.do\" method=\"post\" name=\"log\">\n");
      out.write(" 			<div>\n");
      out.write("				<div style=\"float: right;\">\n");
      out.write("					<input type=\"text\" name=\"userID\" size=\"30\" placeholder=\"아이디\" id=\"userID\" onkeyup=\"noblank(this)\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write(" 			<div>\n");
      out.write("				<div style=\"float: right;\">\n");
      out.write("					<input type=\"password\" name=\"userPW\" size=\"30\" placeholder=\"비밀번호\"	id=\"userPW\" onkeyup=\"noblank(this)\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("				<div>&nbsp;</div>\n");
      out.write("				<div id=\"Warning\"></div>\n");
      out.write(" 			<div>\n");
      out.write("				<div  align=\"right\"><button type=\"button\" onclick=\"checkid()\">LOGIN</button> <br> </div> \n");
      out.write("				<div  align=\"right\"><button type=\"button\" onclick=\"location.href='signAgreeV.jsp'\">SIGNIN</button></div>\n");
      out.write("			</div>\n");
      out.write("			<input type=\"text\" value=\"");
      out.print(request.getParameter("productCode") );
      out.write("\" name=\"productCode\" hidden=\"\">\n");
      out.write(" 		</form>\n");
      out.write(" 	</div>\n");
      out.write(" 		<div style=\"float: right;\">\n");
      out.write(" 		<br><a id=\"hyper\" href = \"\" target =\"popup\" onclick=\"window.open('findIDV.jsp','popup','width=600,height=600'); return false\">아이디/비밀번호 찾기</a>\n");
      out.write(" 		</div>\n");
      out.write(" </div>\n");
      out.write(" \n");
      out.write(" ");
      out.write("\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
