/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-13 07:05:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetailV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/usr/local/Tomcat/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("file:/usr/local/Tomcat/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1645639151000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("     \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.88.1\">\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.1/examples/headers/\">\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link href=\"../assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write(" <!-- 메인홈바  CSS -->\n");
      out.write("<link type=\"text/css\" href=\"css/productlist.css\" rel=\"stylesheet\" >\n");
      out.write("<link href=\"headers.css\" rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<title>ascent</title>\n");
      out.write("<style>\n");
      out.write(".product_view { \n");
      out.write("	position:relative;\n");
      out.write("	padding: 0 0 0 730px;\n");
      out.write("	width:1600px;\n");
      out.write("	box-sizing:border-box;	\n");
      out.write("}\n");
      out.write(".product_view .img{\n");
      out.write("	position: absolute;\n");
      out.write("	padding:50px 0 0 0; \n");
      out.write("	left:200px;\n");
      out.write("	top:0;	\n");
      out.write("}\n");
      out.write(".product_view h2 {\n");
      out.write("margin:100px 0 15px;\n");
      out.write("padding: 0 0 20px;\n");
      out.write("border-bottom:1.5px solid #333;\n");
      out.write("font-size:30px;\n");
      out.write("color:#463D3D;\n");
      out.write("line-height: 26px;\n");
      out.write("}\n");
      out.write(".product_view table th,\n");
      out.write(".product_view table td {\n");
      out.write("	padding:14px 0 ;\n");
      out.write("	font-size: 20px;\n");
      out.write("	color:#444;\n");
      out.write("	text-align:left;\n");
      out.write("}\n");
      out.write(".product_view .btn {\n");
      out.write("padding: 45px 0 0; \n");
      out.write("text-align:center;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".product_view .btn > button{\n");
      out.write("left:200px;\n");
      out.write("display:inline-block;\n");
      out.write("width:126px;\n");
      out.write("height:50px;\n");
      out.write("font-size:20px;\n");
      out.write("border-radius:2px;\n");
      out.write("color:#999191;\n");
      out.write("line-height: 42px;\n");
      out.write("background:#1A0D35;\n");
      out.write("} \n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color:#FFFAF6\">\n");
      out.write("<!-- 메인홈바 -->\n");
      out.write("	<nav id=\"navBar\" class=\"navbar navbar-expand-lg navbar\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("				aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("					\n");
      out.write("				<!-- 상품 카테고리 한눈에 차라락 보여주기  -->\n");
      out.write("					<ul id=\"nav\">\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"main.do\" id=\"navbarDropdown\"\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							Scent </a>\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"allList.do\">All</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sFList.do\">Floral</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sCList.do\">Citrus</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sFRList.do\">Fresh</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sFTList.do\">Fruity</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sWList.do\">Woody</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"sOList.do\">Oriental</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li> \n");
      out.write("				<!-- 상품별로 보여주기  -->\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"main.do\" id=\"navbarDropdown\"\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							Perfume </a>\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"allList.do\">All</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pPList.do\">Eau de perfume</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pTList.do\">Eau de toilette</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pCList.do\">Eau de cologne</a></li>\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"pBList.do\">Body Spray</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					<!-- 1:1문의 ,공지사항, 상품문의  -->\n");
      out.write("					<li><a class=\"nav-link px-2\" href=\"#\">About</a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"noticeBoardList.do\">Notice</a></li>\n");
      out.write("							<!-- <li><a href=\"counselList.do\">Q&A</a></li> -->\n");
      out.write("							");

							if(session.getAttribute("userID") == null){
							
      out.write("\n");
      out.write("							<li><a href=\"logInV.jsp\">Q&A</a></li>\n");
      out.write("							");

							}else if(session.getAttribute("userID") != null){
							
      out.write("\n");
      out.write("							<li><a href=\"counselList.do\">Q&A</a></li>\n");
      out.write("						  ");
 } 
      out.write("\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				</ul>\n");
      out.write("				<!--로고 -->\n");
      out.write("      			  <div class=\"container col-12 col-lg-auto me-lg-auto mb-2 mb-md-0\">\n");
      out.write("   					 <a class=\"navbar-brand\" href=\"main.do\">\n");
      out.write("   					   <img src=\"assets/logo.png\"  alt=\"\" width=\"300\" height=\"150\">\n");
      out.write("  					  </a>\n");
      out.write("				  </div>\n");
      out.write("      			 <!--검색내용  -->\n");
      out.write("				<form  class=\"d-flex\" method=\"post\" action=\"searchProduct.do\" >\n");
      out.write("				<div>\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchText }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\"  class=\"form-control me-2\" placeholder=\"검색하기\" name=\"searchText\" aria-label=\"Search\"> \n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("					<div class=\"text-end\">\n");
      out.write("					\n");
      out.write("					<!--  검색 -->\n");
      out.write("					<div> \n");
      out.write("				<button type=\"submit\" class=\"btn text-white\">\n");
      out.write("                  <svg xmlns=\"http://www.w3.org/2000/svg\"  width=\"20\" height=\"20\" fill=\"currentColor\" class=\"bi bi-search-heart\" viewBox=\"0 0 14 14 \">\n");
      out.write("				  <path d=\"M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z\"/>\n");
      out.write(" 				 <path d=\"M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z\"/>\n");
      out.write("				</svg>\n");
      out.write("				<span class=\"visually-hidden\"></span>\n");
      out.write("                </button>\n");
      out.write("				 </div> \n");
      out.write("				 </div>\n");
      out.write("				</form>\n");
      out.write("				\n");
      out.write("				<!-- 마이페이지 -->\n");
      out.write("					");
 
				 	 if(session.getAttribute("userID") == null){
					
      out.write("\n");
      out.write("					<i class=\"bi bi-person-fill\" style=\"font-size:2.5rem;cursor: pointer;\" onclick = \"location.href='logInV.jsp'\" ></i>\n");
      out.write("					");

					}else if(session.getAttribute("userID") != null){
					
      out.write("\n");
      out.write("					<i class=\"bi bi-person-fill\" style=\"font-size:2.5rem;cursor: pointer;\" onclick = \"location.href='myPageV.jsp'\" ></i>\n");
      out.write("				  ");
 } 
      out.write("\n");
      out.write("				  <!-- 장바구니 -->\n");
      out.write("					<j  class=\"bi bi-bag-heart\" style=\"font-size:2.3rem; cursor: pointer;\" onclick = \"cartListCheckUser()\"></j>\n");
      out.write("					\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("	</nav>\n");
      out.write("	\n");
      out.write("	<!--  상품상세  -->\n");
      out.write("	<div class=\"product_view\">\n");
      out.write("		<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\n");
      out.write("		<table>\n");
      out.write("		<colgroup>\n");
      out.write("	 	<col style=\"width:173px;\">\n");
      out.write("		<col>\n");
      out.write("		</colgroup>\n");
      out.write("		<tbody>\n");
      out.write("		<tr>	<!-- c:foreach는 dao arraylist 쓸때만   -->\n");
      out.write("			<th>브랜드</th>\n");
      out.write("			<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productBrand }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>	\n");
      out.write("			<th>가격</th>\n");
      out.write("			<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productPrice  }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</td>\n");
      out.write("		</tr>\n");
      out.write("		\n");
      out.write("		<tr>\n");
      out.write("			<th>상품명</th>\n");
      out.write("			<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>용량</th>\n");
      out.write("			<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productSize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("ml</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td>\n");
      out.write("				<form name=\"cartForm\" method=\"post\" action=\"cartWrite.do\">\n");
      out.write("				<input type=\"hidden\" name=\"userID\" value=\"");
      out.print(session.getAttribute("userID") );
      out.write("\" >\n");
      out.write("				<input type=\"hidden\" name=\"productCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\n");
      out.write("				<select name=\"cartAmount\" class=\"form-select form-select-lg mb-3\" aria-label=\".form-select-lg example\">\n");
      out.write("				 <option value=\"1\">1 </option>\n");
      out.write("				 <option value=\"2\">2 </option>\n");
      out.write("				 <option value=\"3\">3 </option>\n");
      out.write("				 <option value=\"4\">4 </option>\n");
      out.write("				 <option value=\"5\">5 </option>\n");
      out.write("				 <option value=\"6\">6 </option>\n");
      out.write("				 <option value=\"7\">7 </option>\n");
      out.write("				 <option value=\"8\">8 </option>\n");
      out.write("				 <option value=\"9\">9 </option>\n");
      out.write("				 <option value=\"10\">10 </option>\n");
      out.write("				</select> \n");
      out.write("				<div class=\"btn\">  \n");
      out.write("				<button class=\"btn1\" type=\"button\" onclick=\"cartWriteCheckUser()\">장바구니</button>\n");
      out.write("				</div>\n");
      out.write("				</form>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("		</tbody>\n");
      out.write("		</table>\n");
      out.write("		<div>\n");
      out.write("			<img class=\"img\" width=\"430px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.productImages }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	 \n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("	var cartForm = document.cartForm;\n");
      out.write("	var userID = '");
      out.print(session.getAttribute("userID"));
      out.write("';\n");
      out.write("	var productCode1 = document.cartForm.productCode.value;\n");
      out.write("function cartWriteCheckUser() {\n");
      out.write("	\n");
      out.write("	if (userID != 'null'){\n");
      out.write("		cartForm.submit();\n");
      out.write("		alert(\"장바구니에 담았습니다.\")\n");
      out.write("	}\n");
      out.write("	else{\n");
      out.write("		alert(\"로그인이 필요합니다.\");\n");
      out.write("		location.href='logInV.jsp?productCode='+productCode1;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function cartListCheckUser() {\n");
      out.write("	if (userID != 'null'){\n");
      out.write("		location.href='cartList.do?userID='+userID;\n");
      out.write("	}\n");
      out.write("	else{\n");
      out.write("		alert(\"로그인이 필요합니다.\");\n");
      out.write("		location.href='logInV.jsp';\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function sendProductCodeLogin() {\n");
      out.write("	if (userID != 'null'){\n");
      out.write("		location.href='myPage.jsp'\n");
      out.write("	}\n");
      out.write("	else{\n");
      out.write("		alert(\"로그인이 필요합니다.\");\n");
      out.write("		location.href='logInV.jsp?productCode='+productCode1;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
